config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :songs
  resources :albums
  resources :publishers
  
  root 'publishers#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :publisher
  has_many :songs
  
  validates :name, presence: true, length: { in: 2..50 }
  validates :cover_art, presence: true
  validates :released_on, presence: true, format: { with: /\A\d{4}-\d{2}-\d{2}\z/, message: "should be in the format YYYY-MM-DD" }
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
  has_many :albums, through: :songs
  
  validates :name, presence: true
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :albums
  has_many :songs, through: :albums
  
  validates :name, length: { in: 5..50 }, uniqueness: true
  validates :address, length: { in: 5..50 }
  validates :city, length: { in: 5..50 }
  validates :state, length: { is: 2 }
  validates :zip, format: { with: /\A\d{5}\z/, message: "should be five digits" }
  validates :phone, format: { with: /\A\d{3}-\d{3}-\d{4}\z/, message: "should look like 210-555-1234" }
  validates :url, format: { with: /\Ahttp:\/\/.+\z/, message: "should look like http://www.yahoo.com" }
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
  belongs_to :artist
  
  validates :name, presence: true, length: { in: 5..50 }
  validates :album_id, :artist_id, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @albums = Album.all
    respond_with(@albums)
  end

  def show
    respond_with(@album)
  end

  def new
    @album = Album.new
    respond_with(@album)
  end

  def edit
  end

  def create
    @album = Album.new(album_params)
    @album.save
    respond_with(@album)
  end

  def update
    @album.update(album_params)
    respond_with(@album)
  end

  def destroy
    @album.destroy
    respond_with(@album)
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:name, :cover_art, :publisher_id, :released_on)
    end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @artists = Artist.all
    respond_with(@artists)
  end

  def show
    respond_with(@artist)
  end

  def new
    @artist = Artist.new
    respond_with(@artist)
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.save
    respond_with(@artist)
  end

  def update
    @artist.update(artist_params)
    respond_with(@artist)
  end

  def destroy
    @artist.destroy
    respond_with(@artist)
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @publishers = Publisher.all
    respond_with(@publishers)
  end

  def show
    respond_with(@publisher)
  end

  def new
    @publisher = Publisher.new
    respond_with(@publisher)
  end

  def edit
  end

  def create
    @publisher = Publisher.new(publisher_params)
    @publisher.save
    respond_with(@publisher)
  end

  def update
    @publisher.update(publisher_params)
    respond_with(@publisher)
  end

  def destroy
    @publisher.destroy
    respond_with(@publisher)
  end

  private
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    def publisher_params
      params.require(:publisher).permit(:name, :address, :city, :state, :zip, :phone, :url)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @songs = Song.all
    respond_with(@songs)
  end

  def show
    respond_with(@song)
  end

  def new
    @song = Song.new
    respond_with(@song)
  end

  def edit
  end

  def create
    @song = Song.new(song_params)
    @song.save
    respond_with(@song)
  end

  def update
    @song.update(song_params)
    respond_with(@song)
  end

  def destroy
    @song.destroy
    respond_with(@song)
  end

  private
    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name, :album_id, :artist_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.slim
= form_for @album, html: { class: "form form-horizontal album" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control'
      = f.error_span(:name)
  .form-group
    = f.label :cover_art, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :cover_art, class: 'form-control'
      = f.error_span(:cover_art)
  .form-group
    = f.label :publisher_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :publisher_id, class: 'form-control'
      = f.error_span(:publisher_id)
  .form-group
    = f.label :released_on, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :released_on, class: 'form-control'
      = f.error_span(:released_on)
  hr
  .form-group
    .col-lg-offset-2.col-lg-10
      => f.submit nil, class: 'btn btn-primary'
      = link_to 'Cancel', albums_path, class: 'btn'

app/views/albums/edit.html.slim
.page-header
  h1 Edit Album
  
= render partial: "form"

app/views/albums/index.html.slim
.page-header
  h1
    .pull-right
      = link_to "New", new_album_path, class: 'btn btn-primary'
    | Albums
  
table.table.table-striped
  thead
    tr
      th name
      th publisher
      th released
  tbody
    - @albums.each do |album|
      tr
        td= link_to album.name, album
        td= album.publisher.name
        td= album.released_on

app/views/albums/new.html.slim
.page-header
  h1 New Album
  
= render partial: "form"

app/views/albums/show.html.slim
.page-header
  h1
    .pull-right
      => link_to 'Back', albums_path, class: 'btn btn-default'
      => link_to 'Edit', [:edit, @album], class: 'btn btn-default'
      = link_to 'Delete', @album, method: "delete", data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
    => @album.name
    small.text-muted album

dl.dl-horizontal
  dt Name
  dd= @album.name

  dt Publisher
  dd= link_to @album.publisher.name, @album.publisher

  dt Released
  dd= @album.released_on

hr


.page-header
  h2 Songs
  
dl.dl-horizontal
  dt.text-muted TRACK #
  dd.text-muted NAME
  
  - @album.songs.each_with_index do |song, index|
    dt= index+1
    dd= link_to song.name, song
  
= content_for :sidebar
  img.img-thumbnail(src=@album.cover_art)

app/views/artists/_form.html.slim
= form_for @artist, html: { class: "form form-horizontal artist" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control'
      = f.error_span(:name)
  .form-group
    .col-lg-offset-2.col-lg-10
      => f.submit nil, class: 'btn btn-primary'
      = link_to 'Cancel', artists_path, class: 'btn'

app/views/artists/edit.html.slim
.page-header
  h1 Edit Artist
  
= render partial: "form"

app/views/artists/index.html.slim
.page-header
  h1
    .pull-right
      = link_to "New", new_artist_path, class: 'btn btn-primary'
    | Artists
  
table.table.table-striped
  thead
    tr
      th name
  tbody
    - @artists.each do |artist|
      tr
        td= link_to artist.name, artist

app/views/artists/new.html.slim
.page-header
  h1 New Artist
  
= render partial: "form"

app/views/artists/show.html.slim
.page-header
  h1
    .pull-right
      = link_to 'Back', artists_path, class: 'btn btn-default'
      '
      = link_to 'Edit', [:edit, @artist], class: 'btn btn-default'
      '
      = link_to 'Delete', @artist, method: "delete", data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
    => @artist.name
    small.text-muted artist

dl.dl-horizontal
  dt Name
  dd= @artist.name

hr

.page-header
  h2 Albums

dl.dl-horizontal
  dt NAME
  dd RELEASED
  - @artist.albums.each do |album|
    dt= link_to album.name, album
    dd= album.released_on

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Alamo Records"
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = favicon_link_tag 'favicon.ico'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/"
          = image_tag 'alamorecords.png'
        a.navbar-brand href="/" Alamo Records
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to "Publishers", publishers_path
            li= link_to "Albums", albums_path
            li= link_to "Artists", artists_path

    .container
      .row
        - if content_for?(:sidebar)
          .col-md-9
            = bootstrap_flash
            = yield
          .col-md-3
            = yield(:sidebar)
        - else
          .col-md-12
            = bootstrap_flash
            = yield

    footer
      .container
        .row
          .col-md-2
            ul
              li LATEST
              li ~
          .col-md-2
            ul
              li OUR TEAM
              li= link_to "Daren", "/"
              li= link_to "Jim", "/"
              li= link_to "Peter", "/"
              li= link_to "Brandt", "/"
              li= link_to "Sean", "/"
          .col-md-2
            ul
              li SUPPORT
              li= link_to "Online Support", "/"
              li= link_to "Chat Now", "/"
          .col-md-6
            ul
              li ABOUT
              li Alamo Records sells the hottest vinyl tracks at discount prices to save you gas in the tank and cash in the bank.
    
    div.gutter
            

app/views/publishers/_form.html.slim
= form_for @publisher, html: { class: "form form-horizontal publisher" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control'
      = f.error_span(:name)
  .form-group
    = f.label :address, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :address, class: 'form-control'
      = f.error_span(:address)
  .form-group
    = f.label :city, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :city, class: 'form-control'
      = f.error_span(:city)
  .form-group
    = f.label :state, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :state, class: 'form-control'
      = f.error_span(:state)
  .form-group
    = f.label :zip, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :zip, class: 'form-control'
      = f.error_span(:zip)
  .form-group
    = f.label :phone, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :phone, class: 'form-control'
      = f.error_span(:phone)
  .form-group
    = f.label :url, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :url, class: 'form-control'
      = f.error_span(:url)
  hr
  .form-group
    .col-lg-offset-2.col-lg-10
      => f.submit nil, class: 'btn btn-primary'
      = link_to 'Cancel', publishers_path, class: 'btn'

app/views/publishers/edit.html.slim
.page-header
  h1 Edit Publisher
  
= render partial: "form"

app/views/publishers/index.html.slim
.page-header
  h1
    .pull-right
      = link_to "New", new_publisher_path, class: 'btn btn-primary'
    | Publishers
  
table.table.table-striped
  thead
    tr
      th name
      th address
      th city
      th state
      th zip
      th phone
  tbody
    - @publishers.each do |publisher|
      tr
        td= link_to publisher.name, publisher
        td= publisher.address
        td= publisher.city
        td= publisher.state
        td= publisher.zip
        td= publisher.phone

app/views/publishers/new.html.slim
.page-header
  h1 New Publisher
  
= render partial: "form"

app/views/publishers/show.html.slim
.page-header
  h1
    .pull-right
      = link_to 'Back', publishers_path, class: 'btn btn-default'
      '
      = link_to 'Edit', [:edit, @publisher], class: 'btn btn-default'
      '
      = link_to 'Delete', @publisher, method: "delete", data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
    = @publisher.name

dl.dl-horizontal
  dt Name
  dd= @publisher.name

  dt Address
  dd= @publisher.address

  dt City
  dd= @publisher.city

  dt State
  dd= @publisher.state

  dt Zip
  dd= @publisher.zip

  dt Phone
  dd= @publisher.phone

  dt url
  dd= @publisher.url

hr

= content_for :sidebar
  .well.sidebar-nav.sidebar
    h3 Albums
    ul.list-inline
      - @publisher.albums.each do |album|
        li= link_to album do
          img(src=album.cover_art style="width:50px")

app/views/songs/_form.html.slim
= form_for @song, html: { class: "form form-horizontal song" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control'
      = f.error_span(:name)
  .form-group
    = f.label :album_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.collection_select(:album_id, Album.all, :id, :name, { prompt: "Select an album..." }, class: 'form-control')
      = f.error_span(:album_id)
  .form-group
    = f.label :artist_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.collection_select(:artist_id, Artist.all, :id, :name, { prompt: "Select an artist..."}, class: 'form-control')
      = f.error_span(:artist_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      => f.submit nil, class: 'btn btn-primary'
      = link_to 'Cancel', songs_path, class: 'btn'

app/views/songs/edit.html.slim
.page-header
  h1 Edit Song
  
= render partial: "form"

app/views/songs/index.html.slim
.page-header
  .pull-right
    = link_to "New", new_song_path, class: 'btn btn-primary'
    
  h1 Songs
  
table.table.table-striped
  thead
    tr
      th name
      th album
      th artist
  tbody
    - @songs.each do |song|
      tr
        td= link_to song.name, song
        td= song.album.name
        td= song.artist.name

app/views/songs/new.html.slim
.page-header
  h1 New Song
  
= render partial: "form"

app/views/songs/show.html.slim
.page-header
  h1
    .pull-right    
      = link_to songs_path, class: 'btn btn-default' do
        i.fa.fa-reply>
        span.hidden-xs Back
      '
      = link_to [:edit, @song], class: 'btn btn-default' do
        i.fa.fa-pencil>
        span.hidden-xs Edit
      '
      = link_to @song, method: "delete", data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
        i.fa.fa-trash-o>
        span.hidden-xs Delete
    = @song.name
    small.text-muted.hidden-xs< song

dl.dl-horizontal
  dt Name
  dd= @song.name

  dt Album
  dd= link_to @song.album.name, @song.album

  dt Artist
  dd= link_to @song.artist.name, @song.artist

hr